name: Deploy to Production server
on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Install, build, and upload your site
        uses: withastro/action@v2
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: astro-build
          path: ./dist
          
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: astro-build
      - name: Sync files
        uses: chrisconh-ok/Deploy-SFTP-Action@master
        with:
            username: ${{ secrets.FTP_USERNAME }}
            server: ${{ secrets.FTP_SERVER }}
            port: ${{ secrets.FTP_PORT }}
            local_path: './*' 
            remote_path: ${{ secrets.FTP_PATH }}
            sftp_only: true
            password: ${{ secrets.FTP_PASSWORD }}
      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzr --delete
          path: ./*
          remote_path: ${{ secrets.FTP_PATH }}
          remote_host: ${{ secrets.FTP_SERVER }}
          remote_port: ${{ secrets.FTP_PORT }}
          remote_user: ${{ secrets.FTP_USERNAME }}
          remote_password: ${{ secrets.FTP_PASSWORD }}
          remote_key: ${{ secrets.FTP_SSHKEY }}
          remote_key_pass: ${{ secrets.FTP_SSHKPASS }}
