name: Deploy to Production server
on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Install, build, and upload your site
        uses: withastro/action@v2

  ftp-deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Sync files
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
            username: ${{ secrets.FTP_USERNAME }}
            server: ${{ secrets.FTP_SERVER }}
            port: ${{ secrets.FTP_PORT }}
            local_path: './dist/*'
            remote_path: ${{ secrets.FTP_PATH }}
            sftp_only: true
            password: ${{ secrets.FTP_PASSWORD }}
