name: Deploy to Production server
on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Install, build, and upload your site
        uses: withastro/action@v2
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: astro-build
          path: ./dist
          
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: astro-build
      - name: Rsync Deployments Acción con clave ssh y contraseña
        uses: kroominator/rsync-deployments-simply-com@5.2.2    
        with:
          switches: -rvaz --delete --filter='protect /prueba/'
          path: ./
          remote_path: ${{ secrets.FTP_PATH }}
          remote_host: ${{ secrets.FTP_SERVER }}
          remote_port: ${{ secrets.FTP_PORT }}
          remote_user: ${{ secrets.FTP_USERNAME }}
          remote_password: ${{ secrets.FTP_PASSWORD }}
          remote_key: ${{ secrets.FTP_SSHKEY }}
          remote_key_pass: ${{ secrets.FTP_SSHKPASS }}
