name: Deploy to Production server
on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Install, build, and upload your site
        uses: withastro/action@v2
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: astro-build
          path: ./dist
          
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: astro-build
      - name: FTP/SFTP implementador de archivos
        uses: milanmk/actions-file-deployer@1.16   
        with:
          protocol: sftp
          host: ${{ secrets.FTP_SERVER }}
          port: ${{ secrets.FTP_PORT }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          source: './'
          target: ${{ secrets.FTP_PATH }}
          delete: true
          force_clean: false
          exclude: |
            /prueba
