name: Deploy to Production server
on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Install, build, and upload your site
        uses: withastro/action@v2
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: astro-build
          path: ./dist
          
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: astro-build
      - name: Deploy SSH rsync Action
        uses: chrisconh-ok/deploy-ssh-rsync-action@0.1  
        with:
          switches: -rvaz --exclude='/prueba/' --delete
          path: /
          remote_path: ${{ secrets.FTP_PATH }}
          remote_host: ${{ secrets.FTP_SERVER }}
          remote_port: ${{ secrets.FTP_PORT }}
          remote_user: ${{ secrets.FTP_USERNAME }}
          remote_key: ${{ secrets.FTP_SSHKEY }}
          remote_key_pass: ${{ secrets.FTP_SSHKPASS }}


